name: Docker Image CI

on:
  push:
    branches: [ "v1" ]
  pull_request:
    branches: [ "v1" ]
env:
    USERNAME: ${{ secrets.DOCKER_ID }}
    PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Images
        run: |
          docker build -t elvito2121/vitopass-graphql-node-service .
          docker push elvito2121/vitopass-graphql-node-service
